### ISSUE TITLE
npm/yarn sastrawi not found

### ISSUE THREAD

**Issue by affand20** [damzaky/sastrawijs#1]
saya coba install via npm dan yarn kok sama sama not found ya mas ??

**Comment by damzaky** [comment]
oh maaf, harusnya `npm install sastrawijs`, bukan `sastrawi`, saya lupa ubah, terima kasih atas issuenya, untuk yarn belum saya buat hehe

**Comment by affand20** [comment]
oh pantesan hehe. kalo boleh tau ini pakai algoritma apa ya mas ??

**Comment by damzaky** [comment]
silakan cek di https://github.com/damzaky/sastrawijs#algoritma , sejauh ini, sepengetahuan saya, algoritma ini masih ada masalah sih, saya cuma konversi (port) dari yang bahasa PHP
